Libra/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls import path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()


# Setup the URLs and include login URLs for the browsable API.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('libra/', include('welcome.urls'))
    # ...
]

urlpatterns += staticfiles_urlpatterns()

welcome/urls.py
from django.urls import path

from . import views

app_name = 'welcome'
urlpatterns = [
    path('', views.index, name='index'),
    path('present', views.start_slide_show, name='present')
]

welcome/models.py
from django.db import models

welcome/views.py
from django.http import HttpResponse
import json
from django.template import loader
from pathlib import Path
from libra import Settings
from photos.photos import PhotoConnect, Album

def index(request):
    context = {}
    home = str(Path.home())
    with open('%s/Documents/messages.json' % home, 'r+') as f:
        data = json.load(f)
        if data['had_first'] is False:
            first_vist = True
            data['had_first'] = True
            json.dump(data, f, sort_keys=True, indent=4)
            message = data['message']
            context['con'] = message
    template = loader.get_template('index.html')
    return HttpResponse(template.render(context, request))


def start_slide_show(request):
    if request.method == 'POST':
        settings = Settings()
        if settings.has_internet():
            photos = PhotoConnect()
            session = photos.get_authorized_session()
            album = Album(session, "Libra")
            links = []
            for media_item in album.get_media_items():
                reg = media_item['baseUrl']
                mod = str(media_item['baseUrl'] + "=w1280-h800-c")
                links.append(mod)
            context = {
                'links': json.dumps(links)
            }
            template = loader.get_template('photos.html')
            return HttpResponse(template.render(context, request))
        else:
            #use cache.
            pass
    pass


def first_visit(request):
    home = str(Path.home())
    with open('%s/Documents/messages.json' % home, 'r') as f:
        data = json.load(f)
        message = data['message']

    with open('%s/Documents/messages.json' % home, 'w') as outfile:
        d = data
        d['had_first'] = 'true'
        json.dump(d, outfile, sort_keys=True, indent=4)
    return HttpResponse(message)

welcome/templates/welcome/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Project Libra</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ STATIC_URL }}frontend/bootstrap/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">

    <!-- Theme CSS -->
    <link href="{{ STATIC_URL }}frontend/bootstrap/css/clean-blog.css" rel="stylesheet" type="text/css">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' >
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>


</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'welcome:index' %}">Home</a>
                    </li>
                    <!--<li>
                        <a href="settings.html">Settings</a>
                    </li> -->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('{{STATIC_URL}}frontend/bootstrap/img/test.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading" style="color:#737464">
                        <h1>Merry Christmas!</h1>
                        <hr class="small">
                        <span class="subheading">Known previously as Project Libra</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
          <div class="welcome" align="center">
            <form action="{% url 'welcome:present' %}" method="post">
                {% csrf_token %}
                <button type='submit'>Shuffle</button>
            </form>
          </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                    <ul class="list-inline text-center">
                      <p>Merry Christmas my princess, I love you.</p>
                      <p class="copyright text-muted">Copyright &copy; Matthew Horrigan 2018</p>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <!--jQuery-->
    <script src="{{ STATIC_URL }}frontend/bootstrap/vendor/jquery/jquery.min.js"></script>
    <!--Bootstrap Core JavaScript-->
    <script src="{{ STATIC_URL }}frontend/bootstrap/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--Contact Form JavaScript-->
    <script src="{{ STATIC_URL }}frontend/js/jqBootstrapValidation.js"></script>
    <script src="{{ STATIC_URL }}frontend/js/contact_me.js"></script>

    <!--Theme JavaScript-->
    <script src="{{ STATIC_URL }}frontend/js/clean-blog.min.js"></script>

</body>

</html>

welcome/templates/welcome/photos.html
<!DOCTYPE html>
{% load static %}

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Project Libra</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ STATIC_URL }}frontend/bootstrap/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">

    <!-- Theme CSS -->
    <link href="{{ STATIC_URL }}frontend/bootstrap/css/clean-blog.css" rel="stylesheet" type="text/css">

</head>


<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">

                </button>ss
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'welcome:index' %}">Home</a>
                        <!--<a href="{% url 'welcome:index' %}">Home</a>-->
                    </li>
                    <!--<li>
                        <div>Bar</div>
                    </li>
                    <li>
                        <div>Hello</div>
                    </li>
                    <li>
                        <div>World</div>
                    </li>  -->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <header class="intro-header">
        <div class="container">
            <div class="row">
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <!--<img src="link=w1280-h800-c" class="inlineflex"> -->
      {% csrf_token %}
      {% if links %}
          <img id="image" class="image" src=>
          <script type="text/javascript">
              photos_from_django = {{ links|safe }};
              document.getElementById("image").src=photos_from_django[0];
              photos_from_django.shift();
              setInterval(function() {
                  document.getElementById("image").src=photos_from_django[0];
                  photos_from_django.shift();
              }, 10000)
              </script>
      {% endif %}
    </div>
    <hr>

    <!-- Footer -->
    <!-- jQuery -->
    <script src="{{ STATIC_URL }}frontend/bootstrap/vendor/jquery/jquery.min.js"></script>
    <!--Bootstrap Core JavaScript-->
    <script src="{{ STATIC_URL }}frontend/bootstrap/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--Contact Form JavaScript-->
    <script src="{{ STATIC_URL }}frontend/js/jqBootstrapValidation.js"></script>
    <script src="{{ STATIC_URL }}frontend/js/contact_me.js"></script>

    <!--Theme JavaScript-->
    <script src="{{ STATIC_URL }}frontend/js/clean-blog.min.js"></script>

</body>

</html>

welcome/templates/welcome/settings.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Project Libra</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>
                        <a href="about.html">About</a>
                    </li>
                    <li>
                        <a href="post.html">Sample Post</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('img/test.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Settings</h1>
                        <hr class="small">
                        <span class="subheading">Known previously as Project Libra</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
          <div class="col-md-6">
              <div class="well">Description</div>
          </div>
          <div class="col-md-6">
              <div class="well">
                <label class="switch">
                  <input type="checkbox">
                  <span class="slider round"></span>
                </label>
              </div>
          </div>
          <div class="col-md-6">
              <div class="well">Date</div>
          </div>
          <div class="col-md-6">
              <div class="well">
                <label class="switch">
                  <input type="checkbox">
                  <span class="slider round"></span>
                </label>
              </div>
          </div>
          <div class="col-md-6">
              <div class="well">Where</div>
          </div>
          <div class="col-md-6">
              <div class="well">
                <label class="switch">
                  <input type="checkbox">
                  <span class="slider round"></span>
                </label>
              </div>
          </div>
          <div class="col-md-6">
              <div class="well">Interval (in seconds)</div>
          </div>
          <div class="col-md-6">
              <div class="well">
                <form>
                  <input type="text" id="interval" name="interval" required
                  minlength="2" maxlength="6" size="10" value="15">
              </div>
          </div>
          <div class="col-md-12">
            <div class="well">
              <p>Hello</p>
            </div>
          </div>
      </div>
      <div>
        <div>
          <!---
          <div class="col-md-6">
            <label class="switch">
              <input type="checkbox">
              <span class="slider round"></span>
            </label>
          </div>
          -->
        </div>
      </div>
    <div class="container">
      <div class="row">

      </div>
    </div>
</div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>

    <!-- Theme JavaScript -->
    <script src="js/clean-blog.min.js"></script>

</body>

</html>